### ISSUE TITLE
Date to greece.csv

### ISSUE THREAD

**Issue by themiszamani** [iMEdD-Lab/open-data#1]
Hi

Could you please add a date column to greece csv?
It would be helpful so as to analyze the data.

Regards

**Comment by troboukis** [comment]
Hey, 
The dataset greece.csv displays the current situation in Greece (so the date would be -now-). 
Have you checked greece_cases.csv and greece_deaths.csv ? 
https://github.com/iMEdD-Lab/open-data/blob/master/COVID-19/greece_cases.csv
https://github.com/iMEdD-Lab/open-data/blob/master/COVID-19/greece_deaths.csv
