### ISSUE TITLE
Wrong dating

### ISSUE THREAD

**Issue by Sandbird** [iMEdD-Lab/open-data#10]
What exactly does this mean ?
Dates start on 26/2/2020 and on the 24/1/2021 this happens..and after all those columns we go back to 24/4/2021.
Even if we fix the "21.1" and rename it into "21", all of the sudden we have some new data injected inbetween 2 dates.
Are they to be discarded ? Replace older dates?
What's happening ?
![hmm](https://user-images.githubusercontent.com/204934/140060123-1a4bb3c4-f010-442b-9c44-5ee9b7c8a2a6.png)

-Thank you

**Comment by troboukis** [comment]
You are absolutely right! We have corrected the problem. It was a bug at the code, which has been resolved a few days now! Sorry for the very late response.
