### ISSUE TITLE
regions/country names in "English" or NUTS_iD 

### ISSUE THREAD

**Issue by mohamed-hachaichi** [iMEdD-Lab/open-data#12]
Hello, 

Thanks for the work. However, for someone who do not understant Latin, I found it very hard to read NUTS_3 names. Can you please provide a metadata file (.csv) with the county/county_normalized and the correspondant NUTS_3 ID. 

That would be very helpful. 

Many thanks.

**Comment by troboukis** [comment]
Are you talking about the API? Cause there are English country names.

**Comment by mohamed-hachaichi** [comment]
I'm looking for Greece (or other European countries) at regional level deaths! (please). i don't know yet how to use API, can you suggest a source on how to access to these data? (thank you)

**Comment by troboukis** [comment]
Greece doesn't t publish deaths per region unfortunately. We have reported on the deaths per regional unit in a story but that was when there where 6000 deaths in total. Now it's more that 18000. In any case I ll send you the Nuts 3 English names in a few hours. 

Thanasis Troboukis 
Journalist
Mob: +30 6941556621

**Comment by mohamed-hachaichi** [comment]
Thanks, I m very grateful. Also a csv file would be great. (Or direct me on how to download the data.

Mohamed Hachaichi
PhD 
Hachaichi_mohamed@outlook.com

**Comment by troboukis** [comment]
Dear Mohamed, attached a csv with the relevant NUTS 2 & 3 codes

Best, Thanasis
Thanasis Troboukis
Journalist
+306941556621
