### ISSUE TITLE
Download data

### ISSUE THREAD

**Issue by vpapaioannou** [iMEdD-Lab/open-data#6]
Hi,

How can I download the data? Specifically, I would like to make analysis to view lockdown efficacy. I am thinking of doing this by plotting #test, #deaths/#cases vs time. I think EODY has done something similar recently, but I can't find it.

Thanks,

Vasilis

**Comment by kellykiki** [comment]
Ηi, 

When on the [repository](https://github.com/iMEdD-Lab/open-data/tree/master/COVID-19), click on the .csv file you wish to view. Then, click on the "Raw" button and, finally, right click to save it as .csv file. It should have been downloaded. 

Thank you for reaching out!
